### PR TITLE
Fix typo in initialize with reference to undefined file variable

### PR DESCRIPTION
**Pull request by nardeas**
This fixed issue #39 for me.

### CODE REVIEW

**Review by cusspvz — APPROVED** [review]

**Comment by jakesankey** [comment]
build failed

**Comment by abhaypatil87** [comment]
Locally changing this file fixed the issue for me! Thanks much.

**Comment by jesperronn** [comment]
@andreasur could you pls merge and release new version, so that the change benefits us all?

I hope you have time to do it :)
Thanks!

**Comment by jakesankey** [comment]
Sorry all, I haven't been using Atom lately. I will try to get this published soon. 

Jake

**Comment by jakesankey** [comment]
Please correct the issue with the failing build and I will happily merge.

**Comment by cusspvz** [comment]
@jakesankey could it be an erroneous test?

```coffeescript
 class GitHistoryView extends SelectListView
  
  initialize: (@file) ->
    super()
    @show() if file
```

```js
  GitHistoryView.prototype.initialize = function(file1) {
    this.file = file1;
    GitHistoryView.__super__.initialize.call(this);
    if (file) {
      return this.show();
    }
  };
```

As you may notice, by plugging `@file` on the variable argument so it can be attached to the object, requires to use above as `@file` otherwise it will render an undefined variable.

Is there any chance you can help OP with it? I think your plugin is a great work but unfortunately it isn't working because of a `@`.

**Comment by jakesankey** [comment]
Sorry for the delay. I released this in a patch today. Thanks for the contribution!

**Pull request closed without merging**
